//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCreatorWebSite.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestCreatorEntities : DbContext
    {
        public TestCreatorEntities()
            : base("name=TestCreatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Odpowiedz> Odpowiedz { get; set; }
        public virtual DbSet<Pytania> Pytania { get; set; }
        public virtual DbSet<Stanowiska> Stanowiska { get; set; }
        public virtual DbSet<Testy> Testy { get; set; }
    }
}
