//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCreatorWebSite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wynik
    {
        public int id_wynik { get; set; }
        public float wynik1 { get; set; }
        public int id_test { get; set; }
        public int id_uzytkownik { get; set; }
        public System.DateTime data_sprawdzenia { get; set; }
    }
}
