//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCreatorWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Pytanie
    {
        public int id_pytanie { get; set; }
        public string pytanie1 { get; set; }
        public string odpowiedz { get; set; }
        public bool typ { get; set; }
        public bool isvisible { get; set; }
        public int id_test { get; set; }
    }
}
