//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCreator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pytania
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pytania()
        {
            this.Odpowiedz = new HashSet<Odpowiedz>();
        }
    
        public int id_pytanie { get; set; }
        public string tresc_pytania { get; set; }
        public bool is_visible { get; set; }
        public bool otwarte { get; set; }
        public Nullable<int> id_test { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odpowiedz> Odpowiedz { get; set; }
        public virtual Testy Testy { get; set; }
    }
}
