//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCreator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pytanie
    {
        public long id_pytanie { get; set; }
        public string pytanie1 { get; set; }
        public string odpowiedz { get; set; }
        public Nullable<byte> typ { get; set; }
    }
}
