//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCreator.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestCreatorEntities : DbContext
    {
        public TestCreatorEntities()
            : base("name=TestCreatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Stanowiska> Stanowiska { get; set; }
        public virtual DbSet<Testy> Testy { get; set; }
        public virtual DbSet<Uzytkownicy> Uzytkownicy { get; set; }
    
        public virtual ObjectResult<SysUsersContener> GetAllUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SysUsersContener>("GetAllUsers");
        }
    
        public virtual int DeleteUser(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUser", idParameter);
        }
    
        public virtual int UserActualization(Nullable<long> idUzytkownika, string login, string name, string haslo, Nullable<long> id_rola)
        {
            var idUzytkownikaParameter = idUzytkownika.HasValue ?
                new ObjectParameter("idUzytkownika", idUzytkownika) :
                new ObjectParameter("idUzytkownika", typeof(long));
    
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var hasloParameter = haslo != null ?
                new ObjectParameter("haslo", haslo) :
                new ObjectParameter("haslo", typeof(string));
    
            var id_rolaParameter = id_rola.HasValue ?
                new ObjectParameter("id_rola", id_rola) :
                new ObjectParameter("id_rola", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserActualization", idUzytkownikaParameter, loginParameter, nameParameter, hasloParameter, id_rolaParameter);
        }
    }
}
