//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCreator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testy
    {
        public int id_test { get; set; }
        public string nazwa { get; set; }
        public Nullable<System.DateTime> data_stworzenia { get; set; }
        public bool is_visible { get; set; }
        public Nullable<int> id_stanowisko { get; set; }
    
        public virtual Stanowiska Stanowiska { get; set; }
    }
}
