//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCreator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownicy
    {
        public int id_uzytkownik { get; set; }
        public string login { get; set; }
        public string haslo { get; set; }
        public bool is_visible { get; set; }
        public Nullable<int> id_rola { get; set; }
        public Nullable<System.DateTime> data_dodania { get; set; }
        public string name { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
